title: 别问
url: https://yangqun-git.github.io/
baseurl: ''
cdnurl: ''
description: >
  该去大闹一场喽。

permalink: /:year/:month/:title.html

image: /public/images/mountains.jpg
color: '#dc322f'
google_analytics: 
baidu_analytics:
disqus: yangqun

markdown: kramdown
highlighter: rouge
paginate: 12
paginate_path: "/page/:num"

# 作者信息
author:
  name: yangqun
  email: 987498025@qq.com
  photo: /public/images/avatar.jpeg

# 社交信息
socials:
  - title: Github
    icon: github
    url: https://github.com/yangqun-git
  # - title: Twitter
  #   icon: twitter
  #   url: https://github.com/yangqun-git
  # - title: Youtube
  #   icon: youtube
  #   url: https://github.com/yangqun-git
  # - title: Telegram Group
  #   icon: telegram
  #   url: https://github.com/yangqun-git

# 友链
links:
  # - title: seoui
  #   url: http://blog.seoui.com/
  # - title: Data羊
  #   url: http://www.datayang.com/
  # - title: HongQuan'Blog
  #   url: https://www.devtool.top/
  # - title: 二三克
  #   url: https://same.blog/
  # - title: vzardlloo
  #   url: https://vzardlloo.github.io/
  # - title: Bakumon
  #   url: https://bakumon.me/blog
  # - title: sunzhenyu
  #   url: https://sunzhenyu.net/
  # - title: 代码和段子手
  #   url: http://codefun007.xyz/
  # - title: hweining's garden
  #   url: https://hweining.online/
  # - title: Bakumon
  #   url: https://bakumon.me/blog/
  # - title: 练涛
  #   url: https://blog.liantao.me/

# html 压缩
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]

# sass 解析
sass:
  sass_dir: public/css
  style: compressed

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap